name: CashIO CI 
run-name: ${{github.actor}} running CI 
on: [push]
jobs: 
  CI:
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - run: echo "Running Tests"
      - run: cargo test
      - run: echo "Building for Release"
      - run: cargo rustc -- -D warnings --release --all-features
